## Actividad 6 - Metodo de Selección arriba-abajo

In [27]:
import numpy as np

def repair_func(poblation, capacity, weights):
    for i in range(poblation.shape[0]):
        
        knapsack_full = True if np.dot(weights, poblation[i]) > capacity else False
            
        while knapsack_full == True:
            for j in range(poblation.shape[1]):
                poblation[i, j] = 0
                knapsack_full = False if np.dot(weights, poblation[i]) < capacity else True
                    
        while knapsack_full == False:
            for j in range(poblation.shape[1]):
                poblation[i, j] = 1
                if np.dot(weights, poblation[i]) > capacity:
                    poblation[i, j] = 0
                    knapsack_full = True

def selection_top_down(poblation, x_rate):
    max = int((poblation.shape[0]*x_rate))
    father, mother = range(1,max,2), range(0,max,2)
    return father, mother

poblation = np.random.randint(2, size=(10, 10)) # Cromosomas, objetos = Size
weights = np.random.uniform(1, 10, size=(10))
capacity = np.sum(weights)/2
value = np.random.uniform(1, 100, size=(10))
X_rate = 0.5
repair_func(poblation, capacity, weights)
print("Población Inicial: \n", poblation)
father_id, mother_id = selection_top_down(poblation, X_rate)
print("Padres: \n", poblation[father_id])
print("Madres: \n", poblation[mother_id])

Población Inicial: 
 [[1 1 1 1 0 1 0 0 0 0]
 [1 1 1 1 0 1 0 0 0 0]
 [1 1 1 1 0 0 1 1 0 0]
 [1 1 1 1 0 1 0 0 0 0]
 [1 1 1 1 0 1 0 0 0 0]
 [1 1 1 1 0 1 0 0 0 0]
 [1 1 1 1 0 1 0 0 0 0]
 [0 1 1 1 0 0 0 1 0 1]
 [1 1 1 1 0 1 0 0 0 0]
 [1 1 1 1 0 1 0 0 0 0]]
Padres: 
 [[1 1 1 1 0 1 0 0 0 0]
 [1 1 1 1 0 1 0 0 0 0]]
Madres: 
 [[1 1 1 1 0 1 0 0 0 0]
 [1 1 1 1 0 0 1 1 0 0]
 [1 1 1 1 0 1 0 0 0 0]]


## Actividad 7 - Metodo de Selección aleatoria

In [24]:
import numpy as np
import math

def repair_func(poblation, capacity, weights):
    for i in range(poblation.shape[0]):
        
        knapsack_full = True if np.dot(weights, poblation[i]) > capacity else False
            
        while knapsack_full == True:
            for j in range(poblation.shape[1]):
                poblation[i, j] = 0
                knapsack_full = False if np.dot(weights, poblation[i]) < capacity else True
                    
        while knapsack_full == False:
            for j in range(poblation.shape[1]):
                poblation[i, j] = 1
                if np.dot(weights, poblation[i]) > capacity:
                    poblation[i, j] = 0
                    knapsack_full = True

def selection_top_down(poblation, x_rate):
    max = int((poblation.shape[0]*x_rate))
    father, mother = range(1,max+1,2), range(0,max+1,2)
    return father, mother

def selection_random(poblation, x_rate):
    max = int((poblation.shape[0]*x_rate))
    father, mother = np.random.randint(0,max+1,int(math.floor(max/2))), np.random.randint(0,max+1,int(math.ceil(max/2)))
    print("Seleccionados: ", np.concatenate((father,mother))+1)
    return father, mother

# Input of user
print("Bienvenidos al menu de métodos de selección")
size_def = int(input("Tamaño de la población: "))
length = int(input("Longitud del cromosoma: "))
X_rate = float(input("Tasa de selección (0 a 1): "))

# Create values
poblation = np.random.randint(2, size=(size_def, length)) # Cromosomas, objetos = Size
weights = np.random.uniform(1, 10, size=(length))
capacity = np.sum(weights)/2
value = np.random.uniform(1, 100, size=(length))

# Repair
repair_func(poblation, capacity, weights)
print("Población Inicial: \n", poblation)

# Selection
print("TDP = Metodo de seleccion arriba-abajo")
print("RP = Metodo de seleccion aleatoria")

while (True):
    metodo = input("¿Qué metodo desea seleccionar?")
    if (metodo == "TDP"):
        father_id, mother_id = selection_top_down(poblation, X_rate)
    elif (metodo == "RP"):
        father_id, mother_id = selection_random(poblation, X_rate)
    else:
        print("Opcion no valida intente nuevamente")
        continue
    print("Padres: \n", poblation[father_id])
    print("Madres: \n", poblation[mother_id])
    break

Bienvenidos al menu de métodos de selección
Población Inicial: 
 [[1 1 1 0 0]
 [1 1 1 0 0]
 [1 1 0 0 1]
 [1 1 1 0 0]
 [1 1 0 1 0]
 [1 1 0 0 1]
 [1 1 1 0 0]
 [1 1 1 0 0]
 [1 1 1 0 0]]
TDP = Metodo de seleccion arriba-abajo
RP = Metodo de seleccion aleatoria
Padres: 
 [[1 1 1 0 0]]
Madres: 
 [[1 1 1 0 0]]


## Actividad 8: Selección aleatoria ponderada por rangos

In [18]:
import numpy as np
import bisect as b

def repair_func(poblation, capacity, weights):
    for i in range(poblation.shape[0]):
        
        knapsack_full = True if np.dot(weights, poblation[i]) > capacity else False
            
        while knapsack_full == True:
            for j in range(poblation.shape[1]):
                poblation[i, j] = 0
                knapsack_full = False if np.dot(weights, poblation[i]) < capacity else True
                    
        while knapsack_full == False:
            for j in range(poblation.shape[1]):
                poblation[i, j] = 1
                if np.dot(weights, poblation[i]) > capacity:
                    poblation[i, j] = 0
                    knapsack_full = True

def selection_weighted_random(poblation, x_rate):
    max = int((poblation.shape[0]*x_rate))
    random_selection = np.random.rand(max)
    print("Aleatorio: ", random_selection)
    values = np.array([i for i in range(1,max+1)])
    sum_total = np.sum(values)
    sum_pi = ((max - (values) + 1)/sum_total)
    for i in range(1, sum_pi.shape[0]):
        sum_pi[i] += sum_pi[i-1]
    print("SumPi: ", sum_pi)
    father = []
    mother = []
    for i in range(sum_pi.shape[0]):
        x = b.bisect(sum_pi, random_selection[i])
        print("x: ", x)
        if (i % 2 == 1):
            father.append(x)
        else:
            mother.append(x)
    return father, mother

poblation = np.random.randint(2, size=(10, 10)) # Cromosomas, objetos = Size
weights = np.random.uniform(1, 10, size=(10))
capacity = np.sum(weights)/2
value = np.random.uniform(1, 100, size=(10))
X_rate = 0.5
repair_func(poblation, capacity, weights)
print("Población Inicial: \n", poblation)
father_id, mother_id = selection_weighted_random(poblation, X_rate)
print("Padres: \n", poblation[father_id])
print("Madres: \n", poblation[mother_id])

Población Inicial: 
 [[1 1 0 0 1 0 0 1 0 1]
 [0 1 0 0 1 1 0 1 1 0]
 [1 1 1 1 0 1 0 0 0 0]
 [1 1 0 0 0 1 0 1 0 1]
 [1 1 0 1 0 1 1 0 0 0]
 [1 1 0 0 1 1 0 1 0 0]
 [1 1 1 1 0 1 0 0 0 0]
 [0 1 0 1 1 1 0 0 1 1]
 [1 1 0 1 0 1 1 0 0 0]
 [1 1 1 1 0 1 0 0 0 0]]
Aleatorio:  [0.92129866 0.16598356 0.78169059 0.96933952 0.66713191]
SumPi:  [0.33333333 0.6        0.8        0.93333333 1.        ]
x:  3
x:  0
x:  2
x:  4
x:  2
Padres: 
 [[1 1 0 0 1 0 0 1 0 1]
 [1 1 0 1 0 1 1 0 0 0]]
Madres: 
 [[1 1 0 0 0 1 0 1 0 1]
 [1 1 1 1 0 1 0 0 0 0]
 [1 1 1 1 0 1 0 0 0 0]]


In [20]:
import numpy as np
import math

def repair_func(poblation, capacity, weights):
    for i in range(poblation.shape[0]):
        
        knapsack_full = True if np.dot(weights, poblation[i]) > capacity else False
            
        while knapsack_full == True:
            for j in range(poblation.shape[1]):
                poblation[i, j] = 0
                knapsack_full = False if np.dot(weights, poblation[i]) < capacity else True
                    
        while knapsack_full == False:
            for j in range(poblation.shape[1]):
                poblation[i, j] = 1
                if np.dot(weights, poblation[i]) > capacity:
                    poblation[i, j] = 0
                    knapsack_full = True

def selection_top_down(poblation, x_rate):
    max = int((poblation.shape[0]*x_rate))
    father, mother = range(1,max+1,2), range(0,max+1,2)
    return father, mother

def selection_random(poblation, x_rate):
    max = int((poblation.shape[0]*x_rate))
    father, mother = np.random.randint(0,max+1,int(math.floor(max/2))), np.random.randint(0,max+1,int(math.ceil(max/2)))
    print("Seleccionados: ", np.concatenate((father,mother))+1)
    return father, mother

def selection_rank_weighted_random(poblation, x_rate):
    max = int((poblation.shape[0]*x_rate))
    random_selection = np.random.rand(max)
    print("Aleatorio: ", random_selection)
    values = np.array([i for i in range(1,max+1)])
    sum_total = np.sum(values)
    sum_pi = ((max - (values) + 1)/sum_total)
    for i in range(1, sum_pi.shape[0]):
        sum_pi[i] += sum_pi[i-1]
    print("SumPi: ", sum_pi)
    father = []
    mother = []
    for i in range(sum_pi.shape[0]):
        x = b.bisect(sum_pi, random_selection[i])
        print("x: ", x)
        if (i % 2 == 1):
            father.append(x)
        else:
            mother.append(x)
    return father, mother

# Input of user
print("Bienvenidos al menu de métodos de selección")
size_def = int(input("Tamaño de la población: "))
length = int(input("Longitud del cromosoma: "))
X_rate = float(input("Tasa de selección (0 a 1): "))

# Create values
poblation = np.random.randint(2, size=(size_def, length)) # Cromosomas, objetos = Size
weights = np.random.uniform(1, 10, size=(length))
capacity = np.sum(weights)/2
value = np.random.uniform(1, 100, size=(length))

# Repair
repair_func(poblation, capacity, weights)
print("Población Inicial: \n", poblation)

# Selection
print("TDP = Metodo de seleccion arriba-abajo")
print("RP = Metodo de seleccion aleatoria")
print("RWP = Metodo de seleccion aleatoria ponderado por rangos")

while (True):
    metodo = input("¿Qué metodo desea seleccionar?")
    if (metodo == "TDP"):
        father_id, mother_id = selection_top_down(poblation, X_rate)
    elif (metodo == "RP"):
        father_id, mother_id = selection_random(poblation, X_rate)
    elif (metodo == "RWP"):
        father_id, mother_id = selection_rank_weighted_random(poblation, X_rate)
    else:
        print("Opcion no valida intente nuevamente")
        continue
    print("Padres: \n", poblation[father_id])
    print("Madres: \n", poblation[mother_id])
    break

Bienvenidos al menu de métodos de selección
Población Inicial: 
 [[0 0 1 1 1]
 [1 0 0 1 0]
 [0 0 1 1 1]
 [1 0 0 1 0]
 [0 1 0 1 1]
 [1 0 0 1 0]
 [1 0 0 1 0]
 [1 0 0 1 0]
 [1 0 0 1 0]
 [1 0 0 1 0]]
TDP = Metodo de seleccion arriba-abajo
RP = Metodo de seleccion aleatoria
RWP = Metodo de seleccion aleatoria ponderado por rangos
Aleatorio:  [0.21367681 0.75545711 0.67538514 0.72273403 0.15725454]
SumPi:  [0.33333333 0.6        0.8        0.93333333 1.        ]
x:  0
x:  2
x:  2
x:  2
x:  0
Padres: 
 [[0 0 1 1 1]
 [0 0 1 1 1]]
Madres: 
 [[0 0 1 1 1]
 [0 0 1 1 1]
 [0 0 1 1 1]]


## Actividad 9: Selección aleatoria ponderada por costos

In [46]:
import numpy as np
import bisect as b

def repair_func(poblation, capacity, weights):
    for i in range(poblation.shape[0]):
        
        knapsack_full = True if np.dot(weights, poblation[i]) > capacity else False
            
        while knapsack_full == True:
            for j in range(poblation.shape[1]):
                poblation[i, j] = 0
                knapsack_full = False if np.dot(weights, poblation[i]) < capacity else True
                    
        while knapsack_full == False:
            for j in range(poblation.shape[1]):
                poblation[i, j] = 1
                if np.dot(weights, poblation[i]) > capacity:
                    poblation[i, j] = 0
                    knapsack_full = True

def selection_weighted_cost(poblation, x_rate, cost):
    # How many selected
    max = int((poblation.shape[0]*x_rate))
    random_selection = np.random.rand(max+1)
    
    # Select ids
    not_selected, selected = np.argsort(cost)[:max], np.argsort(cost)[max:]
    fitness_not_selected, fitness_selected = cost[not_selected], cost[selected] # Map fitness
    print("Cromosomas descartados: \n", fitness_not_selected)
    
    # Show minimum from not selected
    index_min = np.argmin(fitness_not_selected)
    print("Cromosoma descartado: ", poblation[not_selected[index_min]])
    print("Fitness del Cromosoma descartado: ", fitness_not_selected[index_min])

    # Normalize cost
    c_n = fitness_selected - fitness_not_selected[index_min]
    print("Valores de C_n: \n", c_n)

    p_n = np.abs(c_n / np.sum(c_n))
    print("valores Pn: \n", p_n)

    for i in range(1, p_n.shape[0]):
        p_n[i] += p_n[i-1]
    print("Sumatoria de las probabilidades: \n", p_n)

    father = []
    mother = []
    for i in range(p_n.shape[0]):
        x = b.bisect(p_n, random_selection[i])
        print("x: ", x)
        if (i % 2 == 1):
            father.append(selected[x])
        else:
            mother.append(selected[x])
    return father, mother

poblation = np.random.randint(2, size=(7, 10)) # Cromosomas, objetos = Size
weights = np.random.uniform(1, 10, size=(10))
capacity = np.sum(weights)/2
value = weights + 5
X_rate = 0.5
repair_func(poblation, capacity, weights)
print("Población Reparada: \n", poblation)
print("Pesos de los objetos: \n", weights)
print("Valores de cada objeto: \n", value)
cost = np.dot(poblation, value)
print("Costo (fitness) de cada cromosoma: \n", cost)
father_id, mother_id = selection_weighted_cost(poblation, X_rate, cost)
print("Padres: \n", poblation[father_id])
print("Madres: \n", poblation[mother_id])

Población Reparada: 
 [[1 1 1 0 0 0 0 1 0 0]
 [1 1 1 0 0 1 0 0 0 0]
 [1 1 0 1 0 0 1 1 0 0]
 [1 1 1 0 0 1 0 0 0 0]
 [1 1 1 0 0 1 0 0 0 0]
 [0 1 1 1 1 1 0 1 0 0]
 [1 1 1 0 0 1 0 0 0 0]]
Pesos de los objetos: 
 [9.91088965 6.92405229 6.68284835 2.42611974 6.00495876 2.1144383
 4.93834879 1.46659361 1.24594233 9.88110952]
Valores de cada objeto: 
 [14.91088965 11.92405229 11.68284835  7.42611974 11.00495876  7.1144383
  9.93834879  6.46659361  6.24594233 14.88110952]
Costo (fitness) de cada cromosoma: 
 [44.9843839  45.63222859 50.66600408 45.63222859 45.63222859 55.61901105
 45.63222859]
Cromosomas descartados: 
 [44.9843839  45.63222859 45.63222859]
Cromosoma descartado:  [1 1 1 0 0 0 0 1 0 0]
Fitness del Cromosoma descartado:  44.984383896267104
Valores de C_n: 
 [ 0.64784469  0.64784469  5.68162018 10.63462715]
valores Pn: 
 [0.03678441 0.03678441 0.32260053 0.60383065]
Sumatoria de las probabilidades: 
 [0.03678441 0.07356882 0.39616935 1.        ]
x:  3
x:  3
x:  3
x:  3
Padres: 
 [[