## Actividad 5 - Función de Aptitud

In [1]:
import numpy as np

def repair_func(poblation, capacity, weights):
    for i in range(poblation.shape[0]):
        
        knapsack_full = True if np.dot(weights, poblation[i]) > capacity else False
            
        while knapsack_full == True:
            for j in range(poblation.shape[1]):
                poblation[i, j] = 0
                knapsack_full = False if np.dot(weights, poblation[i]) < capacity else True
                    
        while knapsack_full == False:
            for j in range(poblation.shape[1]):
                poblation[i, j] = 1
                if np.dot(weights, poblation[i]) > capacity:
                    poblation[i, j] = 0
                    knapsack_full = True

poblation = np.random.randint(2, size=(5, 15)) # Cromosomas, objetos = Size
weights = np.random.uniform(1, 10, size=(15))
capacity = np.sum(weights)/2
value = np.random.uniform(1, 100, size=(15))
print("Valores: ", value)
repair_func(poblation, capacity, weights)
print("Población reparada: \n", poblation)
print("Valor de aptitud de la población reparada: \n", np.dot(poblation, value))

Valores:  [82.99628496 10.21428717 11.08045888 58.40151108 85.17555911 62.684224
 58.91899132 98.4372145  70.76154028 15.91237585 90.68807677 68.98305804
 48.13335176  4.9281587  66.90333603]
Población reparada: 
 [[1 1 1 1 1 1 0 0 1 0 1 0 0 0 0]
 [1 1 1 1 1 1 0 0 1 0 1 0 0 0 0]
 [1 1 1 1 0 1 0 0 1 1 0 1 0 0 0]
 [1 1 1 1 1 1 0 0 1 0 1 0 0 0 0]
 [1 1 1 1 1 1 0 0 1 0 1 0 0 0 0]]
Valor de aptitud de la población reparada: 
 [472.00194225 472.00194225 381.03374026 472.00194225 472.00194225]
