### Actividad 2 - Crear la función de reparación

In [2]:
import numpy as np

def repair_func(poblation, capacity, weights):
    for i in range(poblation.shape[0]):
        
        knapsack_full = True if np.dot(weights, poblation[i]) > capacity else False
            
        while knapsack_full == True:
            for j in range(poblation.shape[1]):
                poblation[i, j] = 0
                knapsack_full = False if np.dot(weights, poblation[i]) < capacity else True
                    
        while knapsack_full == False:
            for j in range(poblation.shape[1]):
                poblation[i, j] = 1
                if np.dot(weights, poblation[i]) > capacity:
                    poblation[i, j] = 0
                    knapsack_full = True

poblation = np.random.randint(2, size=(5, 3)) # Cromosomas, objetos = Size
weights = np.random.uniform(1, 10, size=(3))
capacity = np.sum(weights)/2

print("Capacity\n", capacity)

print("Poblation\n", poblation)
print("Weights\n", weights)
print("Function before: \n", np.dot(poblation, weights))

repair_func(poblation, capacity, weights)
print("------------------------------------------------")

print("Poblation\n", poblation)
print("Function after: \n", np.dot(poblation, weights))

Capacity
 6.513143368740077
Poblation
 [[1 0 0]
 [0 0 1]
 [1 1 0]
 [1 1 1]
 [1 1 0]]
Weights
 [3.52485275 8.4518434  1.04959058]
Function before: 
 [ 3.52485275  1.04959058 11.97669616 13.02628674 11.97669616]
------------------------------------------------
Poblation
 [[1 0 1]
 [1 0 1]
 [1 0 1]
 [1 0 1]
 [1 0 1]]
Function after: 
 [4.57444333 4.57444333 4.57444333 4.57444333 4.57444333]


In [17]:
with open("Dataset-knapsack_100-Obj.txt", "r") as f:
    weights = f.readlines()
    weights = weights[1].split(" ")
    weights = np.array([float(w) for w in weights])

print(weights.shape)

(100,)


In [21]:
print(weights)

[9.30512848 7.03596011 7.77261669 6.78085326 9.55051284 6.98753763
 1.2884311  2.95934247 2.08501292 3.32291962 7.14944865 1.14440137
 8.8647075  4.09729495 2.51678162 5.21710459 8.54811908 3.19363096
 4.76710758 4.72829743 7.62199654 1.99150961 4.54323782 6.95722733
 4.81216923 1.07394228 6.94462127 7.56513892 5.24632914 9.31350535
 1.43054073 1.27288685 6.0374215  2.30493325 9.64215272 1.91810339
 9.52091201 3.29186036 1.33496639 7.93195908 1.97446345 5.07368126
 5.91507965 7.05697019 5.58941775 9.88781791 4.5519686  7.68796459
 4.35618453 3.16362433 6.80763966 9.58410318 9.94545152 9.44535514
 1.82179801 3.77258433 4.40968989 3.62179134 1.11693556 1.13934706
 4.96126604 2.622674   8.68390968 3.82250051 4.22802904 4.44436347
 9.10339076 7.12453849 5.75610016 9.3312227  4.59172823 3.18578813
 4.40865032 9.62851773 6.13653107 3.15106485 3.49689707 9.1724305
 5.42876813 8.54352218 7.12133055 4.01434212 2.25313003 7.82434488
 9.21968357 4.67752834 5.79460247 4.09426753 8.72590074 9.17148

In [26]:
poblation = np.random.randint(2, size=(40, 100)) # Cromosomas, objetos = Size
capacity = np.sum(weights)/2

print("Capacity\n", capacity)

aptitud = np.dot(poblation, weights)
print("Max of function before: \n", np.max(aptitud))
print("Min of function before: \n", np.min(aptitud))
print("Average of function before: \n", np.mean(aptitud))
print("ED of function before: \n", np.std(aptitud))

repair_func(poblation, capacity, weights)
print("------------------------------------------------")

aptitud = np.dot(poblation, weights)
print("Max of function after: \n", np.max(aptitud))
print("Min of function after: \n", np.min(aptitud))
print("Average of function after: \n", np.mean(aptitud))
print("ED of function after: \n", np.std(aptitud))

Capacity
 275.49371592964985
Max of function before: 
 315.75866927784125
Min of function before: 
 210.39058005471503
Average of function before: 
 274.21399797503506
ED of function before: 
 24.85574871854255
------------------------------------------------
Max of function after: 
 275.4753672479122
Min of function after: 
 274.6635097099179
Average of function after: 
 275.23264619342893
ED of function after: 
 0.22572613147170228
